### ISSUE TITLE
Limit option not working

### ISSUE THREAD

**Issue by crimsonpixel** [jdaehne/socialFeedMODX#1]
I have successfully added instagram feed on one of my sites and created my own tpl to display images in keeping with the site, however, the limit property doesn't appear to be working if you want more than 15 images.  Works for less than 15 but not more.

**Comment by jdaehne** [comment]
@crimsonpixel at the moment modx only checks the last 15 images for updates. That means: if you have new images the list will grow, but for existing images in your instagram-acount - only the last 15 images will be importet. We will fix that soon.

**Comment by crimsonpixel** [comment]
Thanks @jdaehne  - can use this extra on a number of sites but will need more than 15 images for some.  Nice extra :)

**Comment by jdaehne** [comment]
@crimsonpixel we changed that to check for the last 100 images.
