### ISSUE TITLE
Only insta?

### ISSUE THREAD

**Issue by mintnl** [jdaehne/socialFeedMODX#11]
Hi, love the idea of a simple feed for clients!

when setting up channels on the .pro site i am only able to configure a instagram stream. Docs are sparse but talk about twitter and FB too. Am I doing something wrong or is only insta enabled?

**Comment by jdaehne** [comment]
@mintnl we plan to integrate facebook, twitter & co ... but at the moment there is no time. Sorry. Because this is a free product it will probably take a while.
