### ISSUE TITLE
"No Media available" in socialFeed

### ISSUE THREAD

**Issue by lotta0** [jdaehne/socialFeedMODX#15]
Dear devs of socialFeed, I was setting up a feed/channel on socialFeed and connecting it to an Instagram account and giving permissions, but even after a day now it does not crawl any Instagram posts. I was succesfully trying it a few weeks before to test, if it would work for a project, but now that I need it, I can't get it to work. Do you maybe have an idea what I might have missed out on?

I checked the feed key / api and feed ID multiple times and started the cron.php several times now, but neither on the channel overview on the socialFeed website, nor on my website it shows anything.

My feed IDs are 183 and 190.

Any help would be highly appreciated!

Thanks and warm regards
Lotta

**Comment by jdaehne** [comment]
@lotta0 i just checked your channels. They look good to me. Can you send me the usernames to this channels? Are theses accounts maybe private?

**Comment by lotta0** [comment]
Dear Jan,

thanks for getting back to me so quickly, even though it is a free extra.

The accounts are @zusammentostedt and @janhinnerkzirkel and they are not private.

Warm regards
Lotta

**Comment by jdaehne** [comment]
@lotta0 i just checked your feeds/channels and all the channels still have the latest images in social feed. Everything seems to work, right? If you have trouple importing the images to your website. MA try our latest update on the the extra (v 1.0.5).
If that does not help - please reopen...
