### ISSUE TITLE
500 Server Error when connecting

### ISSUE THREAD

**Issue by bennyb** [jdaehne/socialFeedMODX#16]
A feed has stopped working but is still saying active within the social feed dashboard.  Looks like it's failed to renew the authentication.  I have tried to create a new feed but when I try and authenticate I get a 500 server error.

**Comment by jdaehne** [comment]
@bennyb  Please provide some more informations:
- channel ID

**Comment by bennyb** [comment]
The channel ID of the one that has just stopped working is 127 and the ID of the new channel that I tried to authenticate is 292

**Comment by jdaehne** [comment]
@bennyb we did some fixes. If you reauthenticate your channel. Everything should work.

**Comment by MisterPaddo** [comment]
Hi @jdaehne,

I'm sorry to open up a closed issue but we ran into this issue again when connecting a new client to Instagram.
In Instagram it tells us that the account is connected, but when returning to https://www.socialfeed.pro/channels/connect/instagram?code=*CODE* I get the 500 | Error message.

My feed ID is 456.

If there is anything else I can provide to help debug the issue please let me know. Thanks in advance!

**Comment by eydolan** [comment]
same my side

**Comment by sebastian-marinescu** [comment]
Same here :(
