### ISSUE TITLE
Cronjob repeated fails

### ISSUE THREAD

**Issue by crimsonpixel** [jdaehne/socialFeedMODX#17]
I'm using cron-job.org to run cronjobs for the socialfeed and have a total of 7 cronjobs for this extra set up.  Five work successfully but two keeps failing.

Looking at the detail for the failed attempt it comes back with:

Fetched URL
https://www.domainname.com/assets/components/socialfeed/cron.php
Status
403 Forbidden

I have checked the folders on the server and these are set with the correct permissions as this site is set up the same as all the others that have successful crons running.

I have tried cloning a successful cronjob to see if that works but it doesn't.  Nor does starting from scratch.

If I run the cron in the browser this works and the feed updates, so not entirely sure what is causing the problem.

Suggestions please :)

**Comment by jdaehne** [comment]
@crimsonpixel i do not understand why you have different cronjobs? Just run a single cronjob for example every 60 minutes.

403 means that something does not allow you to access that file (cron.php). So that does not come from the cron itself. So i would suggest to check the server.

**Comment by crimsonpixel** [comment]
I have a single cronjob for each of the feeds for different websites.

So 7 cronjobs - one for each feed for the 7 different websites.  Each runs once a day.

They are all on the same server so don't understand why 2 repeatedly fail.  I will contact the hosting company for their input.

**Comment by crimsonpixel** [comment]
Just thought I'd give you the response from my hosting company regarding this issue which comes from the cron-jobs.org website - 

"The reason these are being blocked is due to the service using a referrer address which is just a hyphen - this is commonly something used by spam bots and not a genuine user so these are blocked by our firewall"

I really like cron-job.org but can see why this has been blocked by the hosting servers.  I will add these particular cron jobs locally.
