### ISSUE TITLE
Multi sites

### ISSUE THREAD

**Issue by crimsonpixel** [jdaehne/socialFeedMODX#2]
I have created a second instagram channel in a second feed for another site and connected the account, however, this doesn't appear to be pulling in the images at all.

I have run the cron job but nothing appears.

Also there doesn't appear to be a way of deleting a Feed

**Comment by jdaehne** [comment]
@crimsonpixel the issue should now be fixed. You should now see the new images on socialFeed in your feed and channel.

At the moment there is no GUI for deleting a Feed. But you can delete the channels inside a feed. But we will add this Feature to socialFeed asap.

**Comment by crimsonpixel** [comment]
Yep all come through now.  Thanks for sorting so quickly.  Really good extra too :)
