### ISSUE TITLE
Feed keeps failing

### ISSUE THREAD

**Issue by bennyb** [jdaehne/socialFeedMODX#20]
Hi,

I'm using this on a site and it works for about a month and then stops.  In the social feed dashboard it's still saying it's active but if I click on it it has broken links to the images.  The only way I've fixed this is by creating a new feed and adding that to the site, but this has then broken again after about a month.  An example feed is:
/feeds/221

**Comment by eydolan** [comment]
i have the same issue, when i try to connect I also get a 500 error

**Comment by eydolan** [comment]
any news on this still getting 500 error? 

![image](https://github.com/jdaehne/socialFeedMODX/assets/3509999/430e6abc-862f-49ec-8398-1d61a534327c)

**Comment by rsdesign007** [comment]
Hi,

I love the SocialFeed MODX extra, but I'm having the same Issue. It worked fine until recently.

It is happening on every feed that I have setup with Social feed on MODX 2 & 3 on multiple different web servers.

The error seems to be coming from the socialfeed.pro website.  When I've tried to re-authorize the feed I get a 500 error.

https://www.socialfeed.pro/channels/connect/instagram?code=xxxxxx

**500 SERVER ERROR**


![Capture](https://github.com/jdaehne/socialFeedMODX/assets/18093270/6fc140fe-ed3b-44fd-95cc-b31e70c3a09f)


Any idea when this will be fixed?


Thank you!!!

Chris

**Comment by eydolan** [comment]
@rsdesign007 rsdesign007 same issue here, he said its a policy thing and they are trying to resolve it with meta

**Comment by crimsonpixel** [comment]
Appears I am suffering with the same problem and no easy way to reset the authorisation as yet.

**Comment by jdaehne** [comment]
Hi,

Unfortunately, after weeks of efforts with Facebook support, we have now given up in frustration. Unfortunately, we are currently not receiving API authorization for socialFeed. Support cannot tell us why this is the case. Unfortunately, we always receive prefabricated and incomprehensible answers with references to pages of Facebook guidelines.

We have therefore decided to integrate our social media data via the Zapier service in future. We have also created an app for MODX for this purpose: https://extras.modx.com/package/socialzap

You can find the documentation here: https://github.com/QUADRO-web/socialZap
At the bottom of the page there is also a migration guide from socialFeed to socialZap.

We already have this running on a few sites at the moment and it works great.

I hope this helps you too.

Best regards
Jan

**Comment by ovomatik** [comment]
Hi. Thanks for your work.
If I read well and all understand, socialFeed don't work anymore for instagram? For instagram, we must use socialZap?

Salutations
Jérôme

**Comment by sebastian-marinescu** [comment]
Hi @jdaehne, 

I'd also just like a quick info: So instead of socialFeed, we should switch to socialZap?

Best regards, Sebastian
