### ISSUE TITLE
Cronjob failed

### ISSUE THREAD

**Issue by crimsonpixel** [jdaehne/socialFeedMODX#3]
Set up cronjob with cron-job.org but it failed with the following response:

"Additionally, a 403 Forbidden
error was encountered while trying to use an ErrorDocument to handle the request."

The folder is accessible but for some reason the cronjob didn't seem to execute.  I haven't changed anything in the file paths or folders which isn't part of set up.  There is a new image in the instagram account but it hasn't been pulled into the feed on the site.

**Comment by jdaehne** [comment]
@crimsonpixel is the new post in the channel in socialFeed available? Does socialFeed show the new Image there?

**Comment by crimsonpixel** [comment]
No it doesn't show in the feed on socialfeed.pro - its only on instagram

**Comment by jdaehne** [comment]
@crimsonpixel should be fixed now.

**Comment by crimsonpixel** [comment]
Cool - that appears to be working now.  Thanks for fixing.

**Comment by crimsonpixel** [comment]
OK I have 2 cronjobs running for the 2 feeds in SocialFeed.pro.  One has successfully run, whilst the other hasn't.  The one that didn't run does have a new image in the feed on socialFeed but it hasn't been updated on the website.  Got the same error message re 403 Forbidden.  I have checked the API key and Feed key information and that is correct. 

The paths for cronjob is correct too.

**Comment by crimsonpixel** [comment]
Just an update - I pushed this back to the hosting company and found the issue which was related to a deny access rule in the htaccess file for the cronjob.org IP address.  Rule has been removed and now executes as expected.  Thanks
