### ISSUE TITLE
Error from cronjob

### ISSUE THREAD

**Issue by achterbahn** [jdaehne/socialFeedMODX#5]
Some installations of SocialFeed show errors in the MODX error log:

1. case (MODX 2.8.1, SF Ver. 1.0.3-pl)

`core/components/socialfeed/model/socialfeed/socialfeed.class.php : 200) PHP warning: array_merge(): Expected parameter 2 to be an array, null given`
and/or
`core/components/socialfeed/model/socialfeed/socialfeed.class.php : 127) PHP warning: Invalid argument supplied for foreach()`

2. case (MODX 2.7.1, SF Ver. 1.0.3-pl)
`core/components/socialfeed/model/socialfeed/socialfeed.class.php : 127) PHP warning: Invalid argument supplied for foreach()`

In both cases the (single) Instapost is shown on the website.

**Comment by mcnickel** [comment]
Same here (1. case). 

But socialFeed snippet does not return any posts. 
On socialfeed.pro the feed is visible.

**Comment by jdaehne** [comment]
@achterbahn @mcnickel should be fixed with the new version: https://github.com/jdaehne/socialFeedMODX/commit/f8ba6d8ad8a50e9f53c6dfb28c36818fa1271ccc
