### ISSUE TITLE
Feed Stopped getting latest posts

### ISSUE THREAD

**Issue by bennyb** [jdaehne/socialFeedMODX#6]
I have feed that suddenly stopped getting the latest posts.  The Latest Media for the feed within the socialfeed dashboard is also out of date.
I've created a brand new channel and feed and that pulls in the latest posts, but wondering what cause the other one to fail and is it something likely to happen again.
The client did change the insta password, I wouldn't of thought this should effect the API integration, but maybe it does.

**Comment by jdaehne** [comment]
@bennyb Instagram works with access tokens. Each token is valid for about (i think) 60 days. socialFeed updates this acces tokens 15 days before they expire. Maybe socialFeed could not update this token? That should not happen actually. But if your account is not connected anymore. The flag of your account changes from auth to unauth and the link to reauthorize again. So if that should ever happen again, just copy the link and reconnect your account. But actually socialFeed will automaticaly update this token for you. Please let me know if that happens again.

**Comment by bennyb** [comment]
Thanks, where should I see the flag, is this within socialfeed or instagram?

**Comment by jdaehne** [comment]
@bennyb if you go to the channels tab you get a list of all your connexted accounts and each account has a "status" of either "active" or "unauth". 

![image](https://user-images.githubusercontent.com/10563227/101610990-3bf59900-3a09-11eb-820c-3d72c830e3b7.png)

If you click on an "unauth" account you can copy the "Connect-Link" URL and reconnect your account.

**Comment by bennyb** [comment]
The one that's not pulling in the latest content actually has an active status.

**Comment by jdaehne** [comment]
@bennyb that is strange. Can you send us an E-mail with the ID of that channel and i will try to fix this: support@quadro-system.de
