### ISSUE TITLE
Feed pulling in Draft and Deleted Posts.

### ISSUE THREAD

**Issue by QuentinFaulkner** [jdaehne/socialFeedMODX#7]
Hi, love this extra and use it on several websites!

I've got a client who has been creating several draft Instagram posts, and then only publishing one. It seems to be that the Channel is pulling in these posts and I can't bypass/hide them in my feed. I looked into the code as much as I could, but the Published is set to 1 and the Deleted set to 0, so I can't even filter in my TPL. Also, the Properties is always NULL, so no help there either.

Any ideas on what this is and how I can prevent these drafts (and potentially unpublished) posts from appearing. 

Thanks,

Quentin

**Comment by jdaehne** [comment]
@QuentinFaulkner sorry for the late answer. I did not see your post.

I think the quickest way is to mark this items in your database as unpublished. Just set "published" to "0" for every post you do not want to appear on your site.

Best regards,
Jan
