### ISSUE TITLE
Intsagram not updating?

### ISSUE THREAD

**Issue by janice171** [jdaehne/socialFeedMODX#8]
The instagram feed i have set up is not updating.
I have the cron.php set to run once every 5 minutes in cPanel:

*/5 | * | * | * | * | https://mySite.co.uk/assets/components/socialfeed/cron.php

System Settings are all correct.

Snippet call [[!socialFeed? &tpl=`socialFeedInstagram` &limit=`6`]]
All pretty simple but the images have not changed since i first added the extra. Any ideas why and what i can check?

**Comment by jdaehne** [comment]
@janice171 is the channel and feed updated in socialFeed? Did you check it there? Are all images available in your channel on socialfeed.pro?

**Comment by janice171** [comment]
Hi, Yes all images are being updated in the channel on socialfeed.pro

**Comment by jdaehne** [comment]
@janice171 ok, that is good. Then there is maybe something wrong with your cron-job. Did you run https://mySite.co.uk/assets/components/socialfeed/cron.php in your browser? If the images appear: there is something wrong with your cron-syntax.

**Comment by janice171** [comment]
Maybe it is the cron-job. Nothing happens when I run the cron.php - just a blank screen.

**Comment by jdaehne** [comment]
@janice171 if you want you can write me an email to support@quadro-system.de - and grant me access to the manager - then i have a look.

**Comment by janice171** [comment]
That's really kind thanks. I'll have a play around with the cron-jobs first off to see if I can get it working. Thanks again

**Comment by janice171** [comment]
Hi, just to let you know I haven't got this working so emailed you. Just wondering if you received the email? Thanks.

**Comment by crimsonpixel** [comment]
Was this issue resolved as I am experiencing this on a couple of feeds?  Cron job is set correctly but fails to run.  

I use cron-job.org for setting up the crons and this was the error for one of the cronjobs.  It had run successfully the day before but failed this morning with this error:

"
<div><pre>&lt;!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"&gt;
&lt;html&gt;&lt;head&gt;
&lt;title&gt;403 Forbidden&lt;/title&gt;
&lt;/head&gt;&lt;body&gt;
&lt;h1&gt;Forbidden&lt;/h1&gt;
&lt;p&gt;You don't have permission to access this resource.&lt;/p&gt;
&lt;p&gt;Additionally, a 403 Forbidden
error was encountered while trying to use an ErrorDocument to handle the request.&lt;/p&gt;
&lt;/body&gt;&lt;/html&gt;
</pre>
</div>
"

**Comment by pixelbyinch** [comment]
I too am having errors, I love the plugin but suddenly it stopped working.

[2021-06-10 14:43:49] (ERROR @[###hidden###]/components/socialfeed/model/socialfeed/socialfeed.class.php : 200) PHP warning: array_merge(): Expected parameter 2 to be an array, null given
[2021-06-10 14:43:49] (ERROR @[###hidden###]/components/socialfeed/model/socialfeed/socialfeed.class.php : 127) PHP warning: Invalid argument supplied for foreach()

PHP 7.4

**Comment by jdaehne** [comment]
@pixelbyinch should be fixed with the new version 1.0.4: https://github.com/jdaehne/socialFeedMODX/commit/f8ba6d8ad8a50e9f53c6dfb28c36818fa1271ccc
